- send:
    message: Message 1. Send an integer!
- receive:
    key: number
    expect_type: int
    on_failure: retry
- send:
    message: Message 2. Send a string!
- receive:
    key: string
    expect_type: str
    on_failure: retry
- send:
    message: Hello?
- conditional:
    condition: message == 'hello'
    response_if_true:
        - send:
            message: You said hello!
    response_if_false:
        - send:
              message: You did not say hello :(